version: '3'

services:
   mysql:
     image: mysql:5.7
     restart: always
     env_file:
       - .env
   application:
     depends_on:
       - mysql
     build: .
     image: docker.io/dincerkurnaz/dincer
     ports:
       - "3000:3000"
     restart: always
     env_file:
       - .env
     labels:
       kompose.service.type: LoadBalancer
